#!/bin/bash
set -e -x


ROOT_DIR=$(cd "$(dirname "$0")"/.. && pwd)
echo "Root dir: ${ROOT_DIR}"
LINKFLAGS="-extldflags -static -s"

build_app() {
  local _dir=$1
  local _app=$2
  local _arch=$3

  cd "${ROOT_DIR}/cmd/${_dir}"

  [ "$(uname)" != "Darwin" ] && LINKFLAGS="-extldflags -static -s"
  CGO_ENABLED=0 GOARCH=${_arch} go build -ldflags \
    "-X github.com/longhorn/cli/meta.Version=$VERSION \
     -X github.com/longhorn/cli/meta.GitCommit=$GITCOMMIT \
     -X github.com/longhorn/cli/meta.BuildDate=$BUILDDATE \
     $LINKFLAGS" -o ${ROOT_DIR}/bin/${_app}-${_arch}
}

source "${ROOT_DIR}/dapper/version"

mkdir -p "${ROOT_DIR}/bin"
echo "Making binary at ${ROOT_DIR}/bin"

for arch in amd64 arm64; do
  build_app local longhornctl-local ${arch}
  build_app remote longhornctl ${arch}
done
